name: Common Build

on:
  push:
    branches-ignore:
      - develop
      - master
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 16.x

      - run: npm install
        name: Install packages

      - run: npm run lint
        name: Check Code

      - run: npm run build-prod
        name: Build Code
