name: Dev Build and Deploy

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  build_and_deploy:
    environment:
      name: DEV
      url: https://dev.money.bhagavan.tech
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - run: npm install
        name: Install packages

      - run: npm run lint
        name: Check Code

      - run: npm run build-prod
        name: Build code
        env:
          APP_URL: ${{ secrets.APP_URL }}
          APP_KEY: ${{ secrets.APP_KEY }}

      - uses: FirebaseExtended/action-hosting-deploy@v0
        name: Deploy to firebase
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_DEPLOY }}"
          projectId: personal-money-app
          channelId: live
          target: dev
